services:
  - type: web
    name: noteopedia
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:create_app()
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: noteopedia-db
          property: connectionString
databases:
  - name: noteopedia-db
    plan: free
